name: material_you
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dynamic_color: ^1.1.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  provider: ^6.0.2

dependency_overrides:
  material_color_utilities: ^0.1.4

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true